#include <nadir/astro/rinex_obs.hpp>
#include <cmath>
#include <iomanip>
#include <map>
#include <sstream>
namespace nadir::astro { namespace { constexpr std::size_t max_bytes=16U*1024U*1024U,max_lines=1'000'000U;
std::string trim(std::string value){const auto first=value.find_first_not_of(" \t\r");const auto last=value.find_last_not_of(" \t\r");return first==std::string::npos?std::string{}:value.substr(first,last-first+1);}
std::optional<double> measurement(std::string text){text=trim(std::move(text));if(text.empty())return{};for(auto& c:text)if(c=='D'||c=='d')c='E';try{std::size_t used{};const auto value=std::stod(text,&used);return used==text.size()&&std::isfinite(value)?std::optional<double>{value}:std::nullopt;}catch(...){return std::nullopt;}}
}
RinexObservationParseResult parse_rinex_observation_epochs(const std::string& text) { if(text.size()>max_bytes)return{false,{},"RINEX observation exceeds size limit"};std::istringstream input(text);std::string line;bool header{},end{};std::size_t lines{};std::map<char,std::vector<std::string>> types;std::vector<RinexObservationEpoch> epochs;
 auto next=[&](){return static_cast<bool>(std::getline(input,line)) && ++lines<=max_lines;};
 while(next()){if(!header){if(line.find("RINEX VERSION / TYPE")!=std::string::npos)header=true;continue;}if(!end){if(line.find("SYS / # / OBS TYPES")!=std::string::npos){const auto body=line.substr(0,std::min<std::size_t>(60,line.size()));std::istringstream fields(body);char system{};int expected{};if(!(fields>>system>>expected)||expected<0)return RinexObservationParseResult{false,{},"invalid RINEX observation types"};std::string code;while(fields>>code)types[system].push_back(std::move(code));if(types[system].size()>static_cast<std::size_t>(expected))types[system].resize(static_cast<std::size_t>(expected));}if(line.find("END OF HEADER")!=std::string::npos)end=true;continue;}if(line.empty()||line[0]!='>')continue;std::istringstream fields(line.substr(1));int y{},mo{},d{},h{},mi{},flag{},count{};double s{};if(!(fields>>y>>mo>>d>>h>>mi>>s>>flag>>count)||!std::isfinite(s)||y<1900||mo<1||mo>12||d<1||d>31||h<0||h>23||mi<0||mi>59||s<0.0||s>=61.0||flag<0||flag>6||count<0)return{false,{},"invalid RINEX observation epoch"};std::ostringstream epoch;epoch<<std::setfill('0')<<std::setw(4)<<y<<'-'<<std::setw(2)<<mo<<'-'<<std::setw(2)<<d<<'T'<<std::setw(2)<<h<<':'<<std::setw(2)<<mi<<':'<<std::fixed<<std::setprecision(3)<<std::setw(6)<<s;epochs.push_back({epoch.str(),flag,count,{}});if(flag>1)continue;for(int satellite=0;satellite<count;++satellite){if(!next())return{false,{},"truncated RINEX observation epoch"};if(line.size()<3)return{false,{},"invalid RINEX satellite observation"};const auto id=trim(line.substr(0,3));if(id.size()!=3)return{false,{},"invalid RINEX satellite id"};const auto found=types.find(id[0]);if(found==types.end())continue;for(std::size_t index=0;index<found->second.size();++index){const auto offset=3U+16U*index;const auto field=offset<line.size()?line.substr(offset,std::min<std::size_t>(16,line.size()-offset)):std::string{};const auto value=measurement(field.substr(0,std::min<std::size_t>(14,field.size())));if(!value&& !trim(field).empty())return{false,{},"invalid RINEX observation value"};epochs.back().observations.push_back({id,found->second[index],value});}}}
 if(lines>max_lines)return{false,{},"RINEX observation has too many lines"};if(!header||!end||epochs.empty())return{false,{},"missing RINEX observation header or epochs"};return{true,std::move(epochs),{}}; }
} // namespace nadir::astro
